# Ecosapin pipeline description

image: composer:2.0

stages:
  - build
  - deploy

default:
  tags:
    - deploy

Compile:
  stage: build
  only:
    - master
  script:
    - mv $PARAMETER_FILE app/config/parameters.php
#    - composer install
  artifacts:
    paths:
      - app/config/parameters.php
#      - modules
#      - vendor

Deploy:
  stage: deploy
  only:
    - master
  script:
    - ssh-keyscan -t rsa $REMOTE_SERVER >> ~/.ssh/known_hosts
    - cat ~/.ssh/known_hosts
    - rsync -rp --delete-after -arvz --delete --exclude=.git --exclude=.gitlab-ci.yml . $REMOTE_USER@$REMOTE_SERVER:$REMOTE_PATH
